version: '3.7'

services:

  db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: initial_password

  web:
    build: .
    command: >
      /bin/bash -c "bundle install && bundle exec rails s -b 0.0.0.0;"
    volumes:
      - .:/RailsHome
    ports:
      - "3000:3000"
    depends_on:
      - db
